### ISSUE TITLE
IP:PORT

### ISSUE THREAD

**Issue by HelderFSFerreira** [OpenSourceLAN/srcds-log-receiver#1]
Is possible to know the IP and the Port of the server?
I'm trying to connect multiple servers to this module...

**Comment by sirsquidness** [comment]
Yup - ever `data` event emits an object that looks like this:
```
{
   "message": {}, // parsed message contents here
   "receivedFrom": {}, // an instance of the dgram module's RemoteInfo
   "recievedAt": date, // timestamp
   "original": "" // original string received
}
```
So you can use the receivedFrom property to distinguish which server sent it.

**Comment by HelderFSFerreira** [comment]
Yes, totaly my fault!
I'm sorry...
