### ISSUE TITLE
Receiving logs to localhost

### ISSUE THREAD

**Issue by shulinnn** [OpenSourceLAN/srcds-log-receiver#4]
So basically im trying to just make this awesome package run, but it seems that either the logs arent being sent or my app does not work.

```js
var logReceiver = require("srcds-log-receiver");
var options = {
	port: 9871,
    adress: "xxx.xx.xxx.xxx",

};

var receiver = new logReceiver.LogReceiver(options);

receiver.on("data", function(data) {
	if (data.isValid) {
		console.log("Received at " + data.receivedAt.format() + " a log of type " + data.packetType);
		console.log("The message is: " + data.message);
	}
});
receiver.on("invalid", function(invalidMessage) {
	console.log("Got some completely unparseable gargbase: " + invalidMessage);
})
```

The server console :
```
logaddress_list
logaddress_list: 1 entry
xxx.xxx.xxx.xx:9871
```

do you know why it could be happening? Thanks in advance

**Comment by sirsquidness** [comment]
Hello!

The most likely cause is something in your network blocking the connection, or not having a port forward through NAT. If your game server is running on the internet somewhere, and this library is running on your local PC, you will definitely need to have port forwarded through your home NAT

**Comment by shulinnn** [comment]
Hello ! 

Thanks for quick reply. Im pretty new to this networking things.
So i have done the port forwarding for the App on port 9871.
But still no logs, is ther a way to detect something like successful connection ?

Edit : Tried to create a google cloud vps, installed fresh node , opened 9871 port for UDP connections and tested the app , still no logs 😢

**Comment by sirsquidness** [comment]
You can try running Wireshark with a filter like `udp.port == 9871` to see if the log packets are reaching your PC.

**Comment by sirsquidness** [comment]
Also make sure you have `log on` set. Your original post showed that you had the log address set, but didn't say if log was set.

Also the IP address in your `logaddress_add` command needs to be your public internet IP, like what shows up if you visit jsonip.com

**Comment by shulinnn** [comment]
> Also make sure you have `log on` set. Your original post showed that you had the log address set, but didn't say if log was set.
> 
> Also the IP address in your `logaddress_add` command needs to be your public internet IP, like what shows up if you visit jsonip.com
> 
> On 21 April 2021 10:03:24 pm AWST, "Patrik Daňo" ***@***.***> wrote:
> >Hello ! 
> >
> >Thanks for quick reply. Im pretty new to this networking things.
> >So i have done the port forwarding for the App on port 9871.
> >But still no logs, is ther a way to detect something like successful
> >connection ?
> >
> >-- 
> >You are receiving this because you commented.
> >Reply to this email directly or view it on GitHub:
> >https://github.com/OpenSourceLAN/srcds-log-receiver/issues/4#issuecomment-824087291
> 

I can see the logs in the console and in the file too. Tried even super simple log adress http with post request and returned 200 response, still nothing. Could it be issue with csgo server provider?

**Comment by shulinnn** [comment]
> You can try running Wireshark with a filter like `udp.port == 9871` to see if the log packets are reaching your PC.
> […](#)
> On 21 April 2021 10:03:24 pm AWST, "Patrik Daňo" ***@***.***> wrote: Hello ! Thanks for quick reply. Im pretty new to this networking things. So i have done the port forwarding for the App on port 9871. But still no logs, is ther a way to detect something like successful connection ? -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#4 (comment)](https://github.com/OpenSourceLAN/srcds-log-receiver/issues/4#issuecomment-824087291)

If i try this on my Desktop i do get no packets at all. So its probably the issue with ports , i believe
